podMonitoring:
  enabled: true
  #  namespace: monitoring
  labels: {}
  interval: 10s
  timeout: 10s
  scheme: http
  metricRelabeling:
    - action: thing
      modulus: 5
      regex: 'foo.*'
      replacement: thing
      separator: ','
      sourceLabels:
        - app=myapp
        - label2=another
      targetLabel: thing=thing
  proxyUrl: "some-proxy.example.com"
  limits:
    labelNameLength: 10
    labelValueLength: 10
    labels: 5
    samples: 5
  params:
    foo:
      - bar
      - baz
  targetLabels:
    fromPod:
      - from: foo
        to: bar
    metadata:
      - one
      - two
